load("@npm//@bazel/typescript:index.bzl", "ts_project")

ts_project( 
    name = "frontendScripts",
    srcs = ["scripts/frame.ts",
            "scripts/tetris.ts"],
    tsconfig = "//:tsconfig.json"
)